"""Tests for v3.0.8 — public demo script INDEX.md generation (source-level check)."""
from __future__ import annotations

import ast
from pathlib import Path

import pytest

ROOT = Path(__file__).parent.parent
DEMO_SCRIPT = ROOT / "scripts" / "run_public_demo.py"
DEMO_SCRIPT_TEXT = DEMO_SCRIPT.read_text(encoding="utf-8")
DEMO_SCRIPT_LOWER = DEMO_SCRIPT_TEXT.lower()


# ── Source-level checks (fast, no execution) ──────────────────────────────────

def test_demo_script_source_creates_index_md():
    assert "INDEX.md" in DEMO_SCRIPT_TEXT or "README.md" in DEMO_SCRIPT_TEXT, \
        "run_public_demo.py must contain code to create INDEX.md or README.md"


def test_demo_script_source_mentions_semiconductor_pilot_pack():
    assert "semiconductor_pilot_pack" in DEMO_SCRIPT_LOWER, \
        "run_public_demo.py INDEX content must mention semiconductor_pilot_pack"


def test_demo_script_source_mentions_robot_pilot_pack():
    assert "robot_pilot_pack" in DEMO_SCRIPT_LOWER, \
        "run_public_demo.py INDEX content must mention robot_pilot_pack"


def test_demo_script_source_mentions_no_hardware_control():
    assert "no hardware control" in DEMO_SCRIPT_LOWER or \
           "hardware_control_enabled=false" in DEMO_SCRIPT_LOWER, \
        "run_public_demo.py INDEX content must mention no hardware control"


def test_demo_script_source_mentions_recovery_profile_not_generated():
    assert "recovery_profile.json is not generated" in DEMO_SCRIPT_LOWER or \
           "not generated by yieldos" in DEMO_SCRIPT_LOWER, \
        "run_public_demo.py INDEX content must state recovery_profile.json is not generated"


def test_demo_script_has_write_output_index_function():
    assert "_write_output_index" in DEMO_SCRIPT_TEXT, \
        "run_public_demo.py must define _write_output_index function"


def test_demo_script_calls_write_output_index():
    assert "_write_output_index" in DEMO_SCRIPT_TEXT, \
        "run_public_demo.py must call _write_output_index"


def test_demo_script_summary_prints_index_path():
    assert "INDEX.md" in DEMO_SCRIPT_TEXT, \
        "run_public_demo.py summary must print path to INDEX.md"


def test_demo_script_prints_safety_fields():
    assert "recovery_profile_generated=false" in DEMO_SCRIPT_LOWER or \
           "recovery_profile_generated" in DEMO_SCRIPT_LOWER, \
        "run_public_demo.py summary must print recovery_profile_generated=false"


def test_demo_script_prints_candidate_only():
    assert "candidate_only=true" in DEMO_SCRIPT_LOWER or \
           "candidate_only" in DEMO_SCRIPT_LOWER, \
        "run_public_demo.py summary must print candidate_only=true"


# ── Execution check (requires running the demo; use --public-demo marker) ─────

@pytest.mark.public_demo
def test_demo_script_generates_index_md(tmp_path):
    """Actually run the demo script and verify INDEX.md is created."""
    import subprocess
    import sys

    out_dir = str(tmp_path / "public_demo")
    result = subprocess.run(
        [sys.executable, str(DEMO_SCRIPT), "--out", out_dir],
        timeout=600,
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, \
        f"run_public_demo.py failed:\nstdout: {result.stdout}\nstderr: {result.stderr}"

    index_md = Path(out_dir) / "INDEX.md"
    assert index_md.exists(), \
        f"INDEX.md not created at {index_md}"

    content = index_md.read_text(encoding="utf-8").lower()
    assert "semiconductor_pilot_pack" in content, "INDEX.md must mention semiconductor_pilot_pack"
    assert "robot_pilot_pack" in content, "INDEX.md must mention robot_pilot_pack"
    assert "no hardware control" in content, "INDEX.md must mention no hardware control"
    assert "recovery_profile.json is not generated" in content, \
        "INDEX.md must state recovery_profile.json is not generated"
