"""Tests for v3.0.11 -- release artifact hygiene enforcement and dirty archive prevention."""
from __future__ import annotations

import importlib.util
import subprocess
import sys
import zipfile
from pathlib import Path

import pytest

ROOT = Path(__file__).parent.parent
CHECKER_SCRIPT = ROOT / "scripts" / "check_release_artifact.py"
WORKFLOWS = ROOT / ".github" / "workflows"
VERSION = (ROOT / "VERSION").read_text(encoding="utf-8-sig").strip()


def _load_checker():
    spec = importlib.util.spec_from_file_location("check_release_artifact", CHECKER_SCRIPT)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _make_clean_zip(tmp_path: Path, root_name: str = "HAL-YieldOS-v3.0.11-poc-release") -> Path:
    """Create a minimal clean release zip that passes hygiene checks."""
    z = tmp_path / f"{root_name}.zip"
    required = [
        "MANIFEST.json",
        "VERSION",
        "pyproject.toml",
        "README.md",
        "RELEASE_NOTES.md",
        "scripts/check_launch_guard.py",
        "scripts/run_public_demo.py",
        "docs/PUBLIC_SAFETY_BOUNDARY.md",
        ".github/workflows/tests.yml",
        ".github/workflows/public-demo.yml",
    ]
    with zipfile.ZipFile(z, "w") as zf:
        for entry in required:
            zf.writestr(f"{root_name}/{entry}", "placeholder")
    return z


# ── Script existence ──────────────────────────────────────────────────────────

def test_check_release_artifact_script_exists():
    assert CHECKER_SCRIPT.exists(), "scripts/check_release_artifact.py must exist"


# ── Official zip validation (skips if zip not yet built) ─────────────────────

@pytest.mark.packaging
def test_validate_official_zip_passes_after_build():
    """Official zip generated by build_release.py must pass hygiene check."""
    zip_path = ROOT / "dist" / f"HAL-YieldOS-v{VERSION}-poc-release.zip"
    if not zip_path.exists():
        pytest.skip("Release zip not found -- run build_release.py first")
    mod = _load_checker()
    errors = mod.validate_release_artifact(zip_path, expected_version=VERSION)
    assert errors == [], f"Official zip failed hygiene: {errors}"


# ── Dirty archive detection ───────────────────────────────────────────────────

def test_dirty_zip_with_ruff_cache_fails(tmp_path):
    root = "HAL-YieldOS-v3.0.11-poc-release"
    z = _make_clean_zip(tmp_path, root)
    with zipfile.ZipFile(z, "a") as zf:
        zf.writestr(f"{root}/.ruff_cache/v0/CACHEDIR.TAG", "dirty")
    mod = _load_checker()
    errors = mod.validate_release_artifact(z)
    assert any(".ruff_cache" in e for e in errors), \
        f"Expected ruff_cache error, got: {errors}"


def test_dirty_zip_with_build_fails(tmp_path):
    root = "HAL-YieldOS-v3.0.11-poc-release"
    z = _make_clean_zip(tmp_path, root)
    with zipfile.ZipFile(z, "a") as zf:
        zf.writestr(f"{root}/build/lib/yieldos/__init__.py", "dirty")
    mod = _load_checker()
    errors = mod.validate_release_artifact(z)
    assert any("/build/" in e for e in errors), \
        f"Expected build/ error, got: {errors}"


def test_dirty_zip_with_dist_v287_fails(tmp_path):
    root = "HAL-YieldOS-v3.0.11-poc-release"
    z = _make_clean_zip(tmp_path, root)
    with zipfile.ZipFile(z, "a") as zf:
        zf.writestr(f"{root}/dist_v287/old_release.zip", "dirty")
    mod = _load_checker()
    errors = mod.validate_release_artifact(z)
    assert any("dist_v" in e for e in errors), \
        f"Expected dist_v error, got: {errors}"


def test_dirty_zip_with_output_fails(tmp_path):
    root = "HAL-YieldOS-v3.0.11-poc-release"
    z = _make_clean_zip(tmp_path, root)
    with zipfile.ZipFile(z, "a") as zf:
        zf.writestr(f"{root}/output/demo/report.md", "dirty")
    mod = _load_checker()
    errors = mod.validate_release_artifact(z)
    assert any("/output/" in e for e in errors), \
        f"Expected output/ error, got: {errors}"


def test_dirty_zip_with_nested_zip_fails(tmp_path):
    root = "HAL-YieldOS-v3.0.11-poc-release"
    z = _make_clean_zip(tmp_path, root)
    with zipfile.ZipFile(z, "a") as zf:
        zf.writestr(f"{root}/old_release.zip", b"PK\x05\x06" + b"\x00" * 18)
    mod = _load_checker()
    errors = mod.validate_release_artifact(z)
    assert any("NESTED_ZIP" in e or ".zip" in e for e in errors), \
        f"Expected nested zip error, got: {errors}"


def test_dirty_zip_with_pycache_fails(tmp_path):
    root = "HAL-YieldOS-v3.0.11-poc-release"
    z = _make_clean_zip(tmp_path, root)
    with zipfile.ZipFile(z, "a") as zf:
        zf.writestr(f"{root}/yieldos/__pycache__/core.cpython-311.pyc", "dirty")
    mod = _load_checker()
    errors = mod.validate_release_artifact(z)
    assert any("__pycache__" in e or ".pyc" in e for e in errors), \
        f"Expected pycache or pyc error, got: {errors}"


def test_dirty_zip_with_whl_fails(tmp_path):
    root = "HAL-YieldOS-v3.0.11-poc-release"
    z = _make_clean_zip(tmp_path, root)
    with zipfile.ZipFile(z, "a") as zf:
        zf.writestr(f"{root}/dist/hal_yieldos-3.0.11-py3-none-any.whl", "dirty")
    mod = _load_checker()
    errors = mod.validate_release_artifact(z)
    assert any(".whl" in e or "/dist/" in e for e in errors), \
        f"Expected whl or dist/ error, got: {errors}"


def test_dirty_zip_with_tar_gz_fails(tmp_path):
    root = "HAL-YieldOS-v3.0.11-poc-release"
    z = _make_clean_zip(tmp_path, root)
    with zipfile.ZipFile(z, "a") as zf:
        zf.writestr(f"{root}/hal_yieldos-3.0.11.tar.gz", "dirty")
    mod = _load_checker()
    errors = mod.validate_release_artifact(z)
    assert any(".tar.gz" in e for e in errors), \
        f"Expected tar.gz error, got: {errors}"


# ── Clean archive passes ──────────────────────────────────────────────────────

def test_valid_minimal_zip_passes(tmp_path):
    z = _make_clean_zip(tmp_path)
    mod = _load_checker()
    errors = mod.validate_release_artifact(z)
    assert errors == [], f"Clean minimal zip should pass, got: {errors}"


# ── Error reporting quality ───────────────────────────────────────────────────

def test_checker_reports_original_bad_entry_names(tmp_path):
    root = "HAL-YieldOS-v3.0.11-poc-release"
    z = _make_clean_zip(tmp_path, root)
    with zipfile.ZipFile(z, "a") as zf:
        zf.writestr(f"{root}/.ruff_cache/v0/CACHEDIR.TAG", "dirty")
    mod = _load_checker()
    errors = mod.validate_release_artifact(z)
    combined = " ".join(errors)
    assert "CACHEDIR.TAG" in combined or ".ruff_cache" in combined, \
        f"Error should mention bad entry name, got: {errors}"


# ── Exit code tests via subprocess ────────────────────────────────────────────

def test_checker_exits_nonzero_on_dirty(tmp_path):
    root = "HAL-YieldOS-v3.0.11-poc-release"
    z = _make_clean_zip(tmp_path, root)
    with zipfile.ZipFile(z, "a") as zf:
        zf.writestr(f"{root}/.ruff_cache/v0/CACHEDIR.TAG", "dirty")
    result = subprocess.run(
        [sys.executable, str(CHECKER_SCRIPT), str(z)],
        capture_output=True, text=True, timeout=15,
    )
    assert result.returncode != 0, \
        f"checker must exit non-zero on dirty zip, got {result.returncode}"
    assert "FAIL" in result.stdout, \
        f"checker must print FAIL on dirty zip\nstdout: {result.stdout}"


@pytest.mark.release_heavy
def test_checker_exits_zero_on_clean_generated_release_zip():
    """Checker exits 0 on the official zip generated by build_release.py."""
    zip_path = ROOT / "dist" / f"HAL-YieldOS-v{VERSION}-poc-release.zip"
    if not zip_path.exists():
        pytest.skip("Release zip not found -- run build_release.py first")
    result = subprocess.run(
        [sys.executable, str(CHECKER_SCRIPT), str(zip_path)],
        capture_output=True, text=True, timeout=15,
    )
    assert result.returncode == 0, (
        f"checker must exit 0 on official zip\n"
        f"stdout: {result.stdout}\nstderr: {result.stderr}"
    )
    assert "PASS" in result.stdout


# ── Release hygiene workflow ──────────────────────────────────────────────────

def test_release_hygiene_workflow_exists():
    assert (WORKFLOWS / "release-hygiene.yml").exists(), \
        ".github/workflows/release-hygiene.yml must exist"


def test_release_hygiene_workflow_uses_check_release_artifact():
    text = (WORKFLOWS / "release-hygiene.yml").read_text(encoding="utf-8")
    assert "check_release_artifact.py" in text, \
        "release-hygiene.yml must invoke check_release_artifact.py"


def test_release_hygiene_workflow_is_manual():
    text = (WORKFLOWS / "release-hygiene.yml").read_text(encoding="utf-8")
    assert "workflow_dispatch" in text, \
        "release-hygiene.yml must use workflow_dispatch (manual trigger)"


def test_release_hygiene_workflow_builds_release_first():
    text = (WORKFLOWS / "release-hygiene.yml").read_text(encoding="utf-8")
    assert "build_release.py" in text, \
        "release-hygiene.yml must run build_release.py before checking artifact"
