"""
tests/test_release_root_folder_name.py

Verifies that the release zip generated by scripts/build_release.py
uses the correct versioned root folder name (HAL-YieldOS-v<VERSION>-poc-release/).

Uses the shared `release_zip_path` session fixture from conftest.py.
The release archive is built once per pytest session and reused here.

Marker: release_heavy
"""
from __future__ import annotations

import importlib.util
import json
import zipfile
from pathlib import Path

import pytest

pytestmark = pytest.mark.release_heavy

ROOT = Path(__file__).parent.parent


def _load_build_release():
    spec = importlib.util.spec_from_file_location(
        "build_release",
        ROOT / "scripts" / "build_release.py",
    )
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


# ── Root folder name ──────────────────────────────────────────────────────────

def test_all_entries_start_with_versioned_root_folder(release_zip_path):
    mod = _load_build_release()
    expected_prefix = f"{mod.RELEASE_NAME}/"
    with zipfile.ZipFile(release_zip_path) as zf:
        for name in zf.namelist():
            assert name.startswith(expected_prefix), (
                f"Entry {name!r} does not start with versioned root {expected_prefix!r}"
            )


def test_no_entry_starts_with_halyieldos_prefix(release_zip_path):
    with zipfile.ZipFile(release_zip_path) as zf:
        bad = [n for n in zf.namelist() if n.startswith("halyieldos/")]
    assert not bad, (
        f"Release zip must not use stale 'halyieldos/' prefix. Found: {bad[:5]}"
    )


def test_zip_name_contains_current_version(release_zip_path):
    mod = _load_build_release()
    assert mod.VERSION in release_zip_path.name, (
        f"Zip filename {release_zip_path.name!r} must contain current version {mod.VERSION!r}"
    )


# ── MANIFEST.json inside zip ──────────────────────────────────────────────────

def test_manifest_version_matches_current_version(release_zip_path):
    mod = _load_build_release()
    with zipfile.ZipFile(release_zip_path) as zf:
        manifest_data = json.loads(zf.read(f"{mod.RELEASE_NAME}/MANIFEST.json"))
    assert manifest_data["version"] == mod.VERSION, (
        f"MANIFEST.json version {manifest_data['version']!r} != {mod.VERSION!r}"
    )


def test_manifest_release_name_matches_folder(release_zip_path):
    mod = _load_build_release()
    with zipfile.ZipFile(release_zip_path) as zf:
        manifest_data = json.loads(zf.read(f"{mod.RELEASE_NAME}/MANIFEST.json"))
    assert manifest_data.get("release_name") == mod.RELEASE_NAME, (
        f"MANIFEST.json release_name {manifest_data.get('release_name')!r} != {mod.RELEASE_NAME!r}"
    )


def test_manifest_has_excluded_artifact_patterns(release_zip_path):
    mod = _load_build_release()
    with zipfile.ZipFile(release_zip_path) as zf:
        manifest_data = json.loads(zf.read(f"{mod.RELEASE_NAME}/MANIFEST.json"))
    patterns = manifest_data.get("excluded_artifact_patterns")
    assert isinstance(patterns, list) and len(patterns) > 0, (
        "MANIFEST.json must have excluded_artifact_patterns list"
    )


# ── VERSION inside zip ────────────────────────────────────────────────────────

def test_version_file_inside_zip_matches(release_zip_path):
    mod = _load_build_release()
    with zipfile.ZipFile(release_zip_path) as zf:
        version_content = zf.read(f"{mod.RELEASE_NAME}/VERSION").decode("utf-8").strip()
    assert version_content == mod.VERSION, (
        f"VERSION inside zip {version_content!r} != {mod.VERSION!r}"
    )
