"""
tests/test_product_memory_rebinning_demo.py

Verifies the Product Memory Rebinning Killer Demo:
- Sample data files present and correctly structured
- MemoryAnalyzer produces severity=medium → binary FAIL
- reclassification_occurred=true in baseline_vs_yieldos.json
- Direct runner generates same outputs as the CLI
- Enriched baseline_vs_yieldos.json contains capacity breakdown and policy rules
- Functional Yield Essence metadata present in all output files

v2.8.10: Rewritten to use run_product_memory_rebinning_demo_direct() instead of
         CLI subprocess calls. cli_e2e marker removed — now in the default core suite.
         CLI smoke moved to tests/test_product_memory_cli_smoke.py.
"""
from __future__ import annotations

import csv
import json
from pathlib import Path

import pytest

ROOT = Path(__file__).parent.parent
DEMO_SAMPLE = ROOT / "samples" / "product_memory_rebinning_demo"
PKG_DEMO_SAMPLE = ROOT / "yieldos" / "sample_data" / "product_memory_rebinning_demo"

BLOCK_HEALTH_CSV = DEMO_SAMPLE / "block_health.csv"
DEVICE_INFO_JSON = DEMO_SAMPLE / "device_info.json"
BASELINE_POLICY_JSON = DEMO_SAMPLE / "baseline_policy.json"


# ── Module-scoped demo output (one run per module) ─────────────────────────

@pytest.fixture(scope="module")
def product_memory_out(tmp_path_factory) -> Path:
    """Generate product memory rebinning demo once for this module."""
    from yieldos.product_memory_runner import run_product_memory_rebinning_demo_direct
    out = tmp_path_factory.mktemp("product_memory")
    return run_product_memory_rebinning_demo_direct(out_dir=out)


# ── Sample data existence ─────────────────────────────────────────────────────

def test_sample_block_health_csv_exists():
    assert BLOCK_HEALTH_CSV.exists(), f"Missing: {BLOCK_HEALTH_CSV}"


def test_sample_device_info_json_exists():
    assert DEVICE_INFO_JSON.exists(), f"Missing: {DEVICE_INFO_JSON}"


def test_baseline_policy_schema():
    data = json.loads(BASELINE_POLICY_JSON.read_text(encoding="utf-8"))
    assert data["schema"] == "hal.yieldos.demo.baseline_policy.v1"
    assert "rules" in data
    rules = data["rules"]
    assert rules.get("max_runtime_bad_blocks") == 0
    assert rules.get("max_uncorrectable_error_blocks") == 0


def test_block_health_has_runtime_bad_blocks():
    with open(BLOCK_HEALTH_CSV, encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    rtb = [r for r in rows if r.get("is_runtime_bad", "").lower() == "true"]
    assert len(rtb) >= 1, "block_health.csv must contain at least one runtime_bad=true block"


# ── Analyzer output (direct Python, no subprocess) ────────────────────────────

def _run_analyzer():
    from yieldos.domains.memory import MemoryAnalyzer
    return MemoryAnalyzer().analyze(
        input_dir=str(DEMO_SAMPLE),
        case_id="test_product_demo",
        asset_id="NAND_DEMO_32GB_MLC",
    )


def test_analyzer_severity_is_medium_or_high():
    result = _run_analyzer()
    assert result["state"].severity.value in ("medium", "high"), (
        f"Expected medium or high severity for binary FAIL, got: {result['state'].severity.value}"
    )


def test_analyzer_remaining_roles_nonempty():
    result = _run_analyzer()
    remaining = result.get("remaining_roles", [])
    assert len(remaining) > 0, "remaining_roles must be non-empty for reclassification"


def test_analyzer_reclassification_occurred():
    import tempfile

    from yieldos.cli.main import _memory_extra_outputs, _memory_source_data_paths, _run_and_write
    result = _run_analyzer()
    with tempfile.TemporaryDirectory() as tmp:
        extra = _memory_extra_outputs(result)
        _run_and_write(result, tmp, "memory", extra_outputs=extra,
                       source_data_paths=_memory_source_data_paths(str(DEMO_SAMPLE)))
        bvsy = json.loads((Path(tmp) / "baseline_vs_yieldos.json").read_text(encoding="utf-8"))
    assert bvsy["binary_policy_verdict"] == "FAIL"
    assert bvsy["reclassification_occurred"] is True, (
        "reclassification_occurred must be True for the product demo sample"
    )


# ── Direct runner output checks ───────────────────────────────────────────────

def test_product_demo_standard_outputs_exist(product_memory_out):
    required = [
        "functional_passport.json",
        "case_manifest.json",
        "data_quality_report.json",
        "decision_readiness_report.json",
        "evidence_pack.json",
        "analysis_trace.json",
        "baseline_vs_yieldos.json",
        "business_case_summary.json",
    ]
    for f in required:
        assert (product_memory_out / f).exists(), f"{f} not generated by product demo runner"


def test_product_demo_baseline_vs_yieldos_enriched(product_memory_out):
    bvsy = json.loads((product_memory_out / "baseline_vs_yieldos.json").read_text(encoding="utf-8"))
    assert bvsy["binary_policy_verdict"] == "FAIL"
    assert bvsy["reclassification_occurred"] is True
    assert "baseline_policy_rules" in bvsy, "baseline_policy_rules must be in enriched output"
    rfc = bvsy.get("recovered_functional_capacity_estimate", {})
    assert "safe_gb" in rfc, "recovered_functional_capacity_estimate must include safe_gb"
    assert rfc.get("safe_gb", 0) > 0, "safe_gb must be > 0 (reclassified capacity)"
    assert rfc.get("total_raw_gb", 0) > 0, "total_raw_gb must be present"


def test_product_demo_business_case_generated(product_memory_out):
    bcs = json.loads((product_memory_out / "business_case_summary.json").read_text(encoding="utf-8"))
    assert bcs.get("schema") == "hal.yieldos.business_case_summary.v1"


def test_product_demo_functional_yield_essence_present(product_memory_out):
    passport = json.loads((product_memory_out / "functional_passport.json").read_text(encoding="utf-8"))
    data_quality = json.loads((product_memory_out / "data_quality_report.json").read_text(encoding="utf-8"))
    manifest = json.loads((product_memory_out / "case_manifest.json").read_text(encoding="utf-8"))
    readiness = json.loads((product_memory_out / "decision_readiness_report.json").read_text(encoding="utf-8"))

    assert "functional_yield_organizing_principle" in passport, (
        "functional_passport must contain functional_yield_organizing_principle"
    )
    assert "data_sufficiency" in data_quality, (
        "data_quality_report must contain data_sufficiency"
    )
    assert "functional_yield_lineage_summary" in manifest, (
        "case_manifest must contain functional_yield_lineage_summary"
    )
    assert "human_review_preparation" in readiness, (
        "decision_readiness_report must contain human_review_preparation"
    )


def test_product_demo_no_forbidden_terms(product_memory_out):
    all_text = "\n".join(
        p.read_text(encoding="utf-8") for p in product_memory_out.glob("*.json")
    )
    forbidden = [
        "certified_root_cause",
        "confirmed_root_cause",
        "safety_certified",
        "yield_guarantee",
        "automatic_recovery_execution",
    ]
    for term in forbidden:
        assert term not in all_text, f"Forbidden term '{term}' found in product memory demo output"


def test_product_demo_no_hardware_execution(product_memory_out):
    passport = json.loads((product_memory_out / "functional_passport.json").read_text(encoding="utf-8"))
    assert passport.get("hardware_execution_enabled") is False or \
           passport.get("hardware_execution_enabled") is None or \
           "candidate" in str(passport.get("claim_boundary", "")).lower(), (
        "functional_passport must not enable hardware execution"
    )
    readiness = json.loads((product_memory_out / "decision_readiness_report.json").read_text(encoding="utf-8"))
    hrp = readiness.get("human_review_preparation", {})
    assert hrp.get("automatic_decision_enabled") is False, (
        "automatic_decision_enabled must be False"
    )
    assert hrp.get("approval_gate_required") is True, (
        "approval_gate_required must be True"
    )
