"""
yieldos/pilot/contracts.py

Data classes for Pilot Input Contracts.
A PilotContract defines what data a domain needs to run YieldOS analysis.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import List, Optional


@dataclass
class InputField:
    """Describes one required or optional input field / file for a domain pilot."""
    name: str
    description: str
    format: str                          # csv | json | jsonl | txt
    required: bool = True
    columns: Optional[List[str]] = None  # expected CSV columns (if format=csv)
    json_keys: Optional[List[str]] = None  # expected top-level JSON keys (if format=json)
    example_value: Optional[str] = None
    sensitivity: str = "internal"        # public | internal | confidential | restricted
    sanitization_notes: str = ""
    minimum_viable_rows: int = 5         # minimum rows for READY status (Option A: demo-compatible)
    recommended_rows: int = 500          # target for real pilot
    functional_yield_role: str = "evidence_inputs"  # remaining|blocked|valid_conditions|evidence|human_review

    def to_dict(self) -> dict:
        d: dict = {
            "name": self.name,
            "description": self.description,
            "format": self.format,
            "required": self.required,
            "sensitivity": self.sensitivity,
            "minimum_viable_rows": self.minimum_viable_rows,
            "recommended_rows": self.recommended_rows,
            "functional_yield_role": self.functional_yield_role,
        }
        if self.columns:
            d["columns"] = self.columns
        if self.json_keys:
            d["json_keys"] = self.json_keys
        if self.example_value:
            d["example_value"] = self.example_value
        if self.sanitization_notes:
            d["sanitization_notes"] = self.sanitization_notes
        return d


@dataclass
class PilotContract:
    """
    Full definition of what a domain pilot needs.
    Generated by domain_contracts.py; consumed by init_pack.py and readiness.py.
    """
    domain: str
    display_name: str
    organizing_question: str
    input_fields: List[InputField] = field(default_factory=list)
    blocked_claims: List[str] = field(default_factory=list)
    evidence_claims: List[str] = field(default_factory=list)
    min_records: int = 10
    recommended_records: int = 500
    pilot_duration_hint: str = "1–2 weeks"
    notes: str = ""

    @property
    def required_fields(self) -> List[InputField]:
        return [f for f in self.input_fields if f.required]

    @property
    def optional_fields(self) -> List[InputField]:
        return [f for f in self.input_fields if not f.required]

    def functional_yield_mapping(self) -> dict:
        """Map input files to functional yield purposes."""
        mapping: dict = {
            "remaining_functions_inputs": [],
            "blocked_functions_inputs": [],
            "valid_conditions_inputs": [],
            "evidence_inputs": [],
            "human_review_inputs": [],
        }
        for f in self.input_fields:
            role = f.functional_yield_role
            if role in mapping:
                mapping[role].append(f.name)
        return mapping

    def to_dict(self) -> dict:
        return {
            "schema": "hal.yieldos.pilot_contract.v1",
            "domain": self.domain,
            "display_name": self.display_name,
            "organizing_question": self.organizing_question,
            "input_fields": [f.to_dict() for f in self.input_fields],
            "blocked_claims": self.blocked_claims,
            "evidence_claims": self.evidence_claims,
            "min_records": self.min_records,
            "recommended_records": self.recommended_records,
            "pilot_duration_hint": self.pilot_duration_hint,
            "notes": self.notes,
        }
